- name: Docker Containers
  docker_container:
    name: "{{ item.name if item.name is defined else item }}"
    api_version: "{{ item.api_version | default(docker_container_api_version_default) }}"
    auto_remove: "{{ item.auto_remove | default(docker_container_auto_remove_default) }}"
    blkio_weight: "{{ item.blkio_weight | default(omit) }}"
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    cap_drop: "{{ item.cap_drop | default(omit) }}"
    capabilities: "{{ item.capabilities | default(omit) }}"
    cleanup: "{{ item.cleanup | default(docker_container_cleanup_default) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    command: "{{ item.command | default(omit) }}"
    comparisons: "{{ item.comparisons | default(omit) }}"
    cpu_period: "{{ item.cpu_period | default(omit) }}"
    cpu_quota: "{{ item.cpu_quota | default(omit) }}"
    cpu_shares: "{{ item.cpu_shares | default(omit) }}"
    cpuset_cpus: "{{ item.cpuset_cpus | default(omit) }}"
    cpuset_mems: "{{ item.cpuset_mems | default(omit) }}"
    debug: "{{ item.debug | default(docker_container_debug_default) }}"
    detach: "{{ item.detach | default(docker_container_detach_default ) }}"
    device_read_bps: "{{ item.device_read_bps | default(omit) }}"
    device_read_iops: "{{ item.device_read_iops | default(omit) }}"
    device_write_bps: "{{ item.device_write_bps | default(omit) }}"
    device_write_iops: "{{ item.device_write_iops | default(omit) }}"
    devices: "{{ item.devices | default(omit) }}"
    dns_opts: "{{ item.dns_opts | default(omit) }}"
    dns_search_domains: "{{ item.dns_search_domains | default(omit) }}"
    dns_servers: "{{ item.dns_servers | default(omit) }}"
    docker_host: "{{ item.docker_host | default(docker_container_docker_host_default) }}"
    domainname: "{{ item.domainname | default(omit) }}"
    entrypoint: "{{ item.entrypoint | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    env_file: "{{ item.env_file | default(omit) }}"
    etc_hosts: "{{ item.etc_hosts | default(omit) }}"
    exposed_ports: "{{ item.exposed_ports | default(omit) }}"
    force_kill: "{{ item.force_kill | default(docker_container_force_kill_default) }}"
    groups: "{{ item.groups | default(omit) }}"
    healthcheck: "{{ item.healthcheck | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    ignore_image: "{{ item.ignore_image | default(docker_container_ignore_image_default) }}"
    image: "{{ item.image | default(omit) }}"
    init: "{{ item.init | default(docker_container_init_default) }}"
    interactive: "{{ item.interactive | default(docker_container_interactive_default) }}"
    ipc_mode: "{{ item.ipc_mode | default(omit) }}"
    keep_volumes: "{{ item.keep_volumes | default(docker_container_keep_volumes_default) }}"
    kernel_memory: "{{ item.kernel_memory | default(omit) }}"
    kill_signal: "{{ item.kill_signal | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    links: "{{ item.links | default(omit) }}"
    log_driver: "{{ item.log_driver | default(omit) }}"
    log_options: "{{ item.log_options | default(omit) }}"
    mac_address: "{{ item.mac_address | default(omit) }}"
    memory: "{{ item.memory | default(docker_container_memory_default) }}"
    memory_reservation: "{{ item.memory_reservation | default(omit) }}"
    memory_swap: "{{ item.memory_swap | default(omit) }}"
    memory_swappiness: "{{ item.memory_swappiness | default(omit) }}"
    mounts: "{{ item.mounts | default(omit) }}"
    network_mode: "{{ item.network_mode | default(omit)"
    networks: "{{ item.networks | default(omit) }}"
    networks_cli_compatible: "{{ item.networks_cli_compatible | default(omit) }}"
    oom_killer: "{{ item.oom_killer | default(omit) }}"
    oom_score_adj: "{{ item.oom_score_adj | default(omit) }}"
    output_logs: "{{ item.output_logs | default(docker_container_output_logs_default) }}"
    paused: "{{ item.paused | default(docker_container_paused_default) }}"
    pid_mode: "{{ item.pid_mode | default(omit) }}"
    pids_limit: "{{ item.pids_limit | default(omit) }}"
    privileged: "{{ item.privileged | default(docker_container_privileged_default) }}"
    published_ports: "{{ item.published_ports | default(omit) }}"
    pull: "{{ item.pull | default(docker_container_pull_default) }}"
    purge_networks: "{{ item.purge_networks | default(docker_container_purge_networks_default) }}"
    read_only: "{{ item.read_only | default(docker_container_read_only_default) }}"
    recreate: "{{ item.recreate | default(docker_container_recreate_default) }}"
    restart: "{{ item.restart | default(docker_container_restart_default) }}"
    restart_policy: "{{ item.restart_policy | default(omit) }}"
    restart_retries: "{{ item.restart_retries | default(omit) }}"
    runtime: "{{ item.runtime | default(omit) }}"
    security_ports: "{{ item.security_ports | default(omit) }}"
    shm_size: "{{ item.shm_size | default(omit) }}"
    ssl_version: "{{ item.ssl_version | default(omit) }}"
    state: "{{ item.state | default(docker_container_state_default) }}"
    stop_signal: "{{ item.stop_signal | default(omit) }}"
    stop_timeout: "{{ item.stop_timeout | default(omit) }}"
    sysctls: "{{ item.sysctls | default(omit) }}"
    timeout: "{{ item.timeout | default(docker_container_timeout_default) }}"
    tls: "{{ item.tls | default(docker_container_tls_default) }}"
    tls_hostname: "{{ item.tls_hsotname | default(docker_container_tls_hostname_default) }}"
    tmpfs: "{{ item.tmpffs | default(omit) }}"
    trust_image_content: "{{ item.trust_image_content | default(docker_container_trust_image_content_default) }}"
    tty: "{{ item.tty | default(docker_container_tty_default) }}"
    ulimits: "{{ item.ulimits | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    userns_mode: "{{ item.userns_mode | default(omit) }}"
    uts: "{{ item.uts | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(docker_container_validate_certs_default) }}"
    volume_driver: "{{ item.volume_driver | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    volumes_from: "{{ item.volumes_from | default(omit) }}"
    working_dir: "{{ item.working_dir | default(omit) }}"
  loop: "{{ docker_containers }}"
  register: docker_containers_stat

- name: debug
  debug:
    msg: "{{ docker_containers_stat }}"