---
- name: Docker networks
  docker_network:
    name: "{{ item.name if item.name is defined else item }}"
    api_version: "{{ item.api_version | default(docker_network_api_version_default) }}"
    appends: "{{ item.appends | default(docker_network_appends_default) }}"
    attachable: "{{ item.attachable | default(omit) }}"
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    connected: "{{ item.connected | default(omit) }}"
    debug: "{{ item.debug | default(docker_network_debug_default) }}"
    docker_host: "{{ item.docker_host | default(docker_network_docker_host_default) }}"
    driver: "{{ item.driver | default(docker_network_driver_default) }}"
    driver_options: "{{ item.driver_options | default(omit) }}"
    enable_ipv6: "{{ item.enable_ipv6 | default(omit) }}"
    force: "{{ item.force | default(docker_network_force_default) }}"
    internal: "{{ item.internal | default(omit) }}"
    ipam_config: "{{ item.ipam_config | default(omit) }}"
    ipam_driver: "{{ item.ipam_driver | default(omit) }}"
    ipam_driver_options: "{{ item.ipam_driver_options | default(omit) }}"
    ipam_options: "{{ item.ipam_options | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    scope: "{{ item.scope | default(omit) }}"
    ssl_version: "{{ item.ssl_version | default(omit) }}"
    state: "{{ item.state | default(docker_network_state_default) }}"
    timeout: "{{ item.timeout | default(docker_network_timeout_default) }}"
    tls: "{{ item.tls | default(docker_network_tls_default) }}"
    tls_hostname: "{{ item.tls_hostname | default(docker_network_tls_hostname_default) }}"
    validate_certs: "{{ item.validate_certs | default(docker_network_validate_certs_default) }}"
  loop: "{{ docker_networks }}"