---
- name: Docker volumes
  docker_volume:
    volume_name: "{{ item.volume_name if item.volume_name is defined else item }}"
    api_version: "{{ item.api_version | default(docker_volume_api_version_default) }}"
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    debug: "{{ item.debug | default(docker_volume_debug_default) }}"
    docker_host: "{{ item.docker_host | default(docker_volume_docker_host_default) }}"
    driver: "{{ item.driver | default(docker_volume_driver_default) }}"
    driver_options: "{{ item.driver_options | default(omit) }}"
    force: "{{ item.force | default(docker_volume_force_default) }}"
    labels: "{{ item.labels | default(omit) }}"
    recreate: "{{ item.recreate | default(docker_volume_recreate_default) }}"
    ssl_version: "{{ item.ssl_version | default(omit) }}"
    state: "{{ item.state | default(docker_volume_state_default) }}"
    timeout: "{{ item.timeout | default(docker_volume_timeout_default) }}"
    tls: "{{ item.tls | default(docker_volume_tls_default) }}"
    tls_hostname: "{{ item.tls_hostname | default(docker_volume_tls_hostname_default) }}"
    validate_certs: "{{ item.validate_certs | default(docker_volume_validate_certs_default) }}"
  loop: "{{ docker_volumes }}"
  register: docker_volumes_stat

- name: debug
  debug:
    msg: "{{ docker_volumes_stat }}"
  when: docker_containers_debug|bool